name: Test-Linux

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  SOLUTION_FILE_PATH: "./test/Linux"
  SIV3D_VERSION: "0.6.13"
  APP_PATH: "./test/Linux"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Siv3D and build
      uses: Ryoga-exe/Siv3D-Actions@main
      with:
        siv3d-version: ${{ env.SIV3D_VERSION }}
        solution-path: ${{ env.SOLUTION_FILE_PATH }}

    - name: Publish App
      uses: actions/upload-artifact@v3
      with:
        name: App
        path: |
          ${{ env.APP_PATH }}
          !${{ env.APP_PATH }}/build
          !${{ env.APP_PATH }}/resources
          !${{ env.APP_PATH }}/.gitignore
          !${{ env.APP_PATH }}/CMakeList.txt
          !${{ env.APP_PATH }}/*.cpp
          !${{ env.APP_PATH }}/*.hpp
          !${{ env.APP_PATH }}/*.h
